In [2]:
import numpy as np
import pandas as pd
import ast

__Loading files into DataFrames__

In [3]:
movies_metadata = pd.read_csv("../data/raw/movies_metadata.csv", low_memory = False)
credits = pd.read_csv("../data/raw/credits.csv")
keywords = pd.read_csv("../data/raw/keywords.csv")

In [4]:
print("Shape of movies_metadata: ", movies_metadata.shape)
print("Shape of credits: ", credits.shape)
print("Shape of keywords: ", keywords.shape)

Shape of movies_metadata:  (45466, 24)
Shape of credits:  (45476, 3)
Shape of keywords:  (46419, 2)

In [5]:
movies_metadata.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [6]:
credits.head()

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862

In [7]:
keywords.head()

      id                                           keywords
0    862  [{'id': 931, 'name': 'jealousy'}, {'id': 4290,...
1   8844  [{'id': 10090, 'name': 'board game'}, {'id': 1...
2  15602  [{'id': 1495, 'name': 'fishing'}, {'id': 12392...
3  31357  [{'id': 818, 'name': 'based on novel'}, {'id':...
4  11862  [{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...

In [8]:
movies_metadata.dtypes

adult                        str
belongs_to_collection        str
budget                       str
genres                       str
homepage                     str
id                           str
imdb_id                      str
original_language            str
original_title               str
overview                     str
popularity                   str
poster_path                  str
production_companies         str
production_countries         str
release_date                 str
revenue                  float64
runtime                  float64
spoken_languages             str
status                       str
tagline                      str
title                        str
video                     object
vote_average             float64
vote_count               float64
dtype: object

In [9]:
movies_metadata.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [10]:
movies_metadata.drop(columns=['adult', 'belongs_to_collection', 'homepage', 'imdb_id', 'production_countries', 'video', 'status', 'spoken_languages', 'tagline'], inplace = True)

In [11]:
movies_metadata.columns

Index(['budget', 'genres', 'id', 'original_language', 'original_title',
       'overview', 'popularity', 'poster_path', 'production_companies',
       'release_date', 'revenue', 'runtime', 'title', 'vote_average',
       'vote_count'],
      dtype='str')

In [12]:
movies_metadata = movies_metadata[movies_metadata['id'].apply(lambda x: str(x).isdigit())]

In [13]:
movies_metadata['id'] = movies_metadata['id'].astype(int)

In [14]:
movies_metadata = movies_metadata.drop_duplicates(subset='id')
credits = credits.drop_duplicates(subset='id')
keywords = keywords.drop_duplicates(subset='id')

__Merging the three Dataframes__

In [15]:
movies = movies_metadata.merge(credits , on='id').merge(keywords, on='id')

In [16]:
movies.shape

(45432, 18)

In [17]:
movies = movies.dropna(subset=['overview', 'title'])

In [18]:
movies.shape

(44475, 18)

In [19]:
print(movies['genres'].iloc[0])
print(movies['cast'].iloc[0])
print(movies['keywords'].iloc[0])

[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]
[{'cast_id': 14, 'character': 'Woody (voice)', 'credit_id': '52fe4284c3a36847f8024f95', 'gender': 2, 'id': 31, 'name': 'Tom Hanks', 'order': 0, 'profile_path': '/pQFoyx7rp09CJTAb932F2g8Nlho.jpg'}, {'cast_id': 15, 'character': 'Buzz Lightyear (voice)', 'credit_id': '52fe4284c3a36847f8024f99', 'gender': 2, 'id': 12898, 'name': 'Tim Allen', 'order': 1, 'profile_path': '/uX2xVf6pMmPepxnvFWyBtjexzgY.jpg'}, {'cast_id': 16, 'character': 'Mr. Potato Head (voice)', 'credit_id': '52fe4284c3a36847f8024f9d', 'gender': 2, 'id': 7167, 'name': 'Don Rickles', 'order': 2, 'profile_path': '/h5BcaDMPRVLHLDzbQavec4xfSdt.jpg'}, {'cast_id': 17, 'character': 'Slinky Dog (voice)', 'credit_id': '52fe4284c3a36847f8024fa1', 'gender': 2, 'id': 12899, 'name': 'Jim Varney', 'order': 3, 'profile_path': '/eIo2jVVXYgjDtaHoF19Ll9vtW7h.jpg'}, {'cast_id': 18, 'character': 'Rex (voice)', 'credit_id': '52fe4284c3a36847f8024fa5', 'gender': 2, 'id': 12900, 'name': 'Wallace Shawn', 'order': 4, 'profile_path': '/oGE6JqPP2xH4tNORKNqxbNPYi7u.jpg'}, {'cast_id': 19, 'character': 'Hamm (voice)', 'credit_id': '52fe4284c3a36847f8024fa9', 'gender': 2, 'id': 7907, 'name': 'John Ratzenberger', 'order': 5, 'profile_path': '/yGechiKWL6TJDfVE2KPSJYqdMsY.jpg'}, {'cast_id': 20, 'character': 'Bo Peep (voice)', 'credit_id': '52fe4284c3a36847f8024fad', 'gender': 1, 'id': 8873, 'name': 'Annie Potts', 'order': 6, 'profile_path': '/eryXT84RL41jHSJcMy4kS3u9y6w.jpg'}, {'cast_id': 26, 'character': 'Andy (voice)', 'credit_id': '52fe4284c3a36847f8024fc1', 'gender': 0, 'id': 1116442, 'name': 'John Morris', 'order': 7, 'profile_path': '/vYGyvK4LzeaUCoNSHtsuqJUY15M.jpg'}, {'cast_id': 22, 'character': 'Sid (voice)', 'credit_id': '52fe4284c3a36847f8024fb1', 'gender': 2, 'id': 12901, 'name': 'Erik von Detten', 'order': 8, 'profile_path': '/twnF1ZaJ1FUNUuo6xLXwcxjayBE.jpg'}, {'cast_id': 23, 'character': 'Mrs. Davis (voice)', 'credit_id': '52fe4284c3a36847f8024fb5', 'gender': 1, 'id': 12133, 'name': 'Laurie Metcalf', 'order': 9, 'profile_path': '/unMMIT60eoBM2sN2nyR7EZ2BvvD.jpg'}, {'cast_id': 24, 'character': 'Sergeant (voice)', 'credit_id': '52fe4284c3a36847f8024fb9', 'gender': 2, 'id': 8655, 'name': 'R. Lee Ermey', 'order': 10, 'profile_path': '/r8GBqFBjypLUP9VVqDqfZ7wYbSs.jpg'}, {'cast_id': 25, 'character': 'Hannah (voice)', 'credit_id': '52fe4284c3a36847f8024fbd', 'gender': 1, 'id': 12903, 'name': 'Sarah Freeman', 'order': 11, 'profile_path': None}, {'cast_id': 27, 'character': 'TV Announcer (voice)', 'credit_id': '52fe4284c3a36847f8024fc5', 'gender': 2, 'id': 37221, 'name': 'Penn Jillette', 'order': 12, 'profile_path': '/zmAaXUdx12NRsssgHbk1T31j2x9.jpg'}]
[{'id': 931, 'name': 'jealousy'}, {'id': 4290, 'name': 'toy'}, {'id': 5202, 'name': 'boy'}, {'id': 6054, 'name': 'friendship'}, {'id': 9713, 'name': 'friends'}, {'id': 9823, 'name': 'rivalry'}, {'id': 165503, 'name': 'boy next door'}, {'id': 170722, 'name': 'new toy'}, {'id': 187065, 'name': 'toy comes to life'}]

In [20]:
def parse_names(text):
    try:
        parsed = ast.literal_eval(text)
        return [item['name'] for item in parsed]
    except:
        return [] 
    
def get_top_cast(text):
    try:
        parsed = ast.literal_eval(text)
        return [item['name'] for item in parsed[:3]]
    except:
        return []
    
def get_director(text):
    try:
        parsed = ast.literal_eval(text)
        for item in parsed:
            if item['job'] == 'Director':
                return item['name']
        
    except:
        return " "

In [21]:
movies['genres'] = movies['genres'].apply(parse_names)
movies['keywords'] = movies['keywords'].apply(parse_names)
movies['cast'] = movies['cast'].apply(get_top_cast)
movies['director'] = movies['crew'].apply(get_director)

In [22]:
movies = movies.drop(columns=['crew'])

In [23]:
movies[['title', 'genres', 'cast', 'director', 'keywords', 'overview']].head(3)

,title,genres,cast,director,keywords,overview
0,Toy Story,"[Animation, Comedy, Family]","[Tom Hanks, Tim Allen, Don Rickles]",John Lasseter,"[jealousy, toy, boy, friendship, friends, riva...","Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,"[Adventure, Fantasy, Family]","[Robin Williams, Jonathan Hyde, Kirsten Dunst]",Joe Johnston,"[board game, disappearance, based on children'...",When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,"[Romance, Comedy]","[Walter Matthau, Jack Lemmon, Ann-Margret]",Howard Deutch,"[fishing, best friend, duringcreditsstinger, o...",A family wedding reignites the ancient feud be...

In [24]:
movies['release_year'] = pd.to_datetime(movies['release_date'], errors='coerce').dt.year

In [25]:
movies['release_year'] = movies['release_year'].fillna(0).astype(int)

In [26]:
movies.drop(columns=['release_date'], inplace=True)

In [27]:
movies[['title', 'release_year']].head()

                         title  release_year
0                    Toy Story          1995
1                      Jumanji          1995
2             Grumpier Old Men          1995
3            Waiting to Exhale          1995
4  Father of the Bride Part II          1995

In [29]:
def create_tags(row):
    genres = ' '.join(row['genres'])
    keywords = ' '.join(row['keywords'])
    cast = ' '.join(row['cast'])
    director = row['director']
    overview = row['overview']
    
    return genres + ' ' + keywords + ' '+  cast + ' ' + overview + ' '

In [ ]:
movies['tags'] = movies.apply(create_tags, axis=1)

In [33]:
movies[['title', 'tags']].head()

,title,tags
0,Toy Story,Animation Comedy Family jealousy toy boy frien...
1,Jumanji,Adventure Fantasy Family board game disappeara...
2,Grumpier Old Men,Romance Comedy fishing best friend duringcredi...
3,Waiting to Exhale,Comedy Drama Romance based on novel interracia...
4,Father of the Bride Part II,Comedy baby midlife crisis confidence aging da...

In [36]:
movies['tags'] = movies['tags'].str.lower().str.strip()

In [37]:
movies[['title', 'tags']].head()

,title,tags
0,Toy Story,animation comedy family jealousy toy boy frien...
1,Jumanji,adventure fantasy family board game disappeara...
2,Grumpier Old Men,romance comedy fishing best friend duringcredi...
3,Waiting to Exhale,comedy drama romance based on novel interracia...
4,Father of the Bride Part II,comedy baby midlife crisis confidence aging da...

In [39]:
movies.to_csv('../data/processed/movies_cleaned.csv', index=False)

In [41]:
print(movies.columns)
print(movies.shape)

Index(['budget', 'genres', 'id', 'original_language', 'original_title',
       'overview', 'popularity', 'poster_path', 'production_companies',
       'revenue', 'runtime', 'title', 'vote_average', 'vote_count', 'cast',
       'keywords', 'director', 'release_year', 'tags'],
      dtype='str')
(44475, 19)